config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "about"=>"homes#about"
    get "search" => "searches#search"
    resources :items, only: [:index,:show]
    resources :genres, only: [:show]
    resource :customers, only: [] do
      member do
        get :my_page, action: :show
        get 'information/edit', action: :edit
        patch :information, action: :update
        get :confirm
        patch :withdraw
      end
    end
    resources :cart_items, except: [:new,:show,:edit] do
      collection do
        delete :all_destroy
      end
    end
    resources :orders, except: [:edit,:update,:destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
    resources :shipping_addresses, except: [:new,:show]
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update] do
      member do
        get :customer
      end
    end
    resources :order_details, only: [:update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre
  has_one_attached :image

  def add_tax_price
    (price*1.1).floor
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @item = Item.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @item = Item.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @item = Item.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :admin_login_confirm

  def index
    @items = Item.all.page(params[:page]).per(10) #10項目毎にページネート
    @item = Item.new
    #@genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @item_new = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
  end

#price_before_tax

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/_form.html.erb
<% items.each do |item| %>
<%= link_to item_path(item.id) do %>
<div class="m-4">
  <div class="mb-2">
    <%= image_tag item.image, size: '200x200' %>
  </div>
  <P><strong><%= link_to item.name, item_path(item.id) %></strong></P>
  <P><strong>￥<%= item.add_tax_price.to_s(:delimited) %></strong></P>
</div>
<% end %>
<% end %>

app/views/admin/items/edit.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>商品編集</strong>
    </h4>
    <div class="col-md-8"></div>
  </div>
  <div class="m-md-2"><br></div>
    <%= form_with model: @item, url: admin_item_path(@item) do |f| %>
      <div class="form-group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :image, '商品名' %></div>
        <div class="col-md-8"><%= f.file_field :image, accept: "image/*", required: true %></div>
      </div>

      <div class="form-group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :name, '商品名' %></div>
        <div class="col-md-8"><%= f.text_field :name, placeholder: "商品名", required: true, size: "44" %></div>
      </div>

      <div class="form-group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :introduction, '商品説明' %></div>
        <div class="col-md-8"><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", required: true, size: "46x10" %></div>
      </div>

      <div class="form-group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :genre_id, 'ジャンル' %></div>
        <div class="col-md-8"><%= f.select :genre_id, options_from_collection_for_select(Genre.all, :id, :genre_name),prompt: "-- 選択してください --", required: true, class: "w-50" %></div>
      </div>

       <div class="form-group row">
        <div class="col-md-3"></div>
        <div class="col-md-1 text-left"><%= f.label :price, '税抜価格' %></div>
        <div class="col-md-8"><%= f.number_field :price, min: 0, placeholder: "1000", required: true, class: "w-50" %>円</div>
      </div>

       <div class="form-group row">
         <div class="col-md-3"></div>
         <div class="col-md-2 text-left">販売ステータス</div>
         <div class="col-md-7">
           <%= f.radio_button :is_active, true %>
           <%= f.label :is_active, '販売中' %>

           <%= f.radio_button :is_active, false %>
           <%= f.label :is_active, '販売停止中' %>
         </div>
       </div>

    <div class="row">
      <div class="action center-block mx-auto">
        <%= f.submit '変更を保存', class: "btn btn-success" %>
      </div>
    <% end %>
    </div>


</div>

app/views/admin/items/index.html.erb
<div class="container">
  <div class="m-md-2"><br>
  <div class="row">
    <h4 class="col-md-2 mx-auto text-center" style="background-color:#DDD">
      <strong>商品一覧</strong>
    </h4>
    <div class="col-md-5 mx-auto text-right">
      <%= link_to "+", new_admin_item_path, class: 'btn btn-outline-secondary rounded-circle p-0　box-shadow' %>
    </div>
  </div>

  <diV class="m-md-2"><br></diV>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-1 mx-auto text-left">
      <strong>商品ID</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>商品名</strong>
    </div>
    <div class="col-md-1 mx-auto text-left">
      <strong>税抜価格</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>ジャンル</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>ステータス</strong>
    </div>
    <div class="col-md-1"></div>
  </div>

  <% @items.each do |item| %>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-1 mx-auto text-left"><%= item.id %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= link_to item.name, admin_item_path(item.id) %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-1 mx-auto text-left"><%= item.price.to_s(:delimited) %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= item.genre.genre_name %>
      <div class="col-md-1"><br></div>
    </div>
    <% if item.is_active == true %>
      <div class="col-md-2 mx-auto text-left text-success">
        <strong><%= '販売中' %></strong>
      </div>
    <% else %>
      <div class="col-md-2 mx-auto text-left text-secondary">
        <strong><%= '販売停止中' %></strong>
      </div>
    <% end %>
    <div class="col-md-1"></div>
  </div>
  <% end %>

  <!--ページネーション追加-->
  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2 mx-auto text-left">
      <%= paginate @items %>
    </div>
    <div class="col-md-5"></div>
  </div>

</div>

app/views/admin/items/new.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>商品新規登録</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

  <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :image, '商品画像' %></div>
      <div class="col-md-8"><%= f.file_field :image, accept: "image/*", required: true %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :name, '商品名' %></div>
      <div class="col-md-8"><%= f.text_field :name, placeholder: "商品名", required: true, size: "44" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :introduction, '商品説明' %></div>
      <div class="col-md-8"><%= f.text_area :introduction, placeholder: "ここに説明文を記述します", required: true, size: "46x10" %></div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :genre_id, 'ジャンル' %></div>
      <div class="col-md-8"><%= f.collection_select :genre_id, @genres, :id, :genre_name, prompt: "-- 選択してください --", required: true, class: "w-50" %></div>
    </div>
    <!--:name-->

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-1 text-left"><%= f.label :price, '税抜価格' %></div>
      <div class="col-md-8"><%= f.number_field :price, min: 0, placeholder: "1000", required: true, class: "w-50" %>円</div>
    </div>

    <div class="form-group row">
      <div class="col-md-3"></div>
      <div class="col-md-2 text-left">販売ステータス</div>
      <div class="col-md-7">
        <%= f.radio_button :is_active, true %>
        <%= f.label :is_active, '販売中' %>

        <%= f.radio_button :is_active, false %>
        <%= f.label :is_active, '販売停止中' %>
      </div>
    </div>
    <div class="row">
      <div class="action center-block mx-auto">
      <%= f.submit '新規登録', class: "btn btn-success" %>
      </div>
    </div>
  <% end %>

    </div>
  </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
  <div class="m-md-2"><br></div>
  <div class="row">
    <div class="col-md-2"></div>
    <h4 class="col-md-2 mx-auto text-center">
      <strong>商品詳細</strong>
    </h4>

    <div class="col-md-8"></div>
  </div>

  <div class="m-md-2"><br></div>

    <div class="row">
      <div class="col-md-5 mx-auto">
        <%= image_tag @item.image, size:'400x300' %>
    </div>
    <div class="col-md-7 mx-auto">
      <table class="information">
        <tr>
          <th>商品名</th>
          <!-- 下の記号はノーブレイクスペースと読みます -->
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @item.name %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>商品説明</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @item.introduction %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>ジャンル</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @item.genre.genre_name %></td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>税込価格</br>
              (税抜価格)</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <td><%= @item.add_tax_price.to_s(:delimited) %>
              (<%= @item.price.to_s(:delimited) %>)円</td>
        </tr>

        <td class="m-md-1"><br></td>

        <tr>
          <th>販売ステータス</th>
          <td>&nbsp;&nbsp;&nbsp;</td>
          <% if @item.is_active == true %>
            <td class="text-success">
              <strong><%= '販売中' %></strong>
            </td>
          <% else %>
            <td class="text-secondary">
              <strong><%= '販売停止中' %></strong>
            </td>
          <% end %>
        </tr>
      </table>
    </div>
  </div>

  <div class="m-md-1"><br></div>

  <div class="row">
    <div class="action center-block mx-auto">
      <%= link_to '編集する',edit_admin_item_path(@item), class: 'btn btn-success' %>
    </div>
  </div>
</div>