config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "about"=>"homes#about"
    get "search" => "searches#search"
    resources :items, only: [:index,:show]
    resources :genres, only: [:show]
    resource :customers, only: [] do
      member do
        get :my_page, action: :show
        get 'information/edit', action: :edit
        patch :information, action: :update
        get :confirm
        patch :withdraw
      end
    end
    resources :cart_items, except: [:new,:show,:edit] do
      collection do
        delete :all_destroy
      end
    end
    resources :orders, except: [:edit,:update,:destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
    resources :shipping_addresses, except: [:new,:show]
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update] do
      member do
        get :customer
      end
    end
    resources :order_details, only: [:update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_way: {
    credit_card: 0,
    transfer: 1}
  enum order_status: {
    payment_wait: 0,
    payment_confirm: 1,
    production: 2,
    preparing_delivery: 3,
    delivered: 4
    }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :admin_login_confirm

  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
  end

  def update
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: params[:id])
    @order.update(order_params)
    if @order.order_status == "payment_confirm"
      @order_details.update_all(product_status: 1)
    end
    redirect_to admin_order_path(@order)
  end

  def customer
    @order = Order.find(params[:id])
    @customer = @order.customer
    @orders = @customer.orders.page(params[:page]).per(10)
  end

  private

  def order_params
    params.require(:order).permit(:order_status)
  end
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/views/admin/orders/customer.html.erb
<div class="col-4 offset-1 mt-4">
  <h4 class="col-8 text-center" style="background:#ddd">
    <strong><%= @customer.last_name + @customer.first_name %></strong>さんの<strong>注文履歴</strong>
  </h4>
</div>
<div class="container">
  <table class="table">
    <thead class="table-secondary">
      <tr>
        <th class="text-center">購入日時</th>
        <th style="width: 20%">注文個数</th>
        <th>注文ステータス</th>
      </tr>
    </thead>
    <% @orders.each do |order| %>
      <tbody>
        <tr>
          <td class="text-center">
            <%= link_to admin_order_path(order.id), class:"text-dark" do %>
              <%= l order.created_at, format: :long %>
            <% end %>
          </td>
          <td><%= order.order_details.sum(:quantity) %></td>
          <td><%= order.order_status_i18n %></td>
        </tr>
      </tbody>
    <% end %>

  </table>

  <!--ページネーション追加-->
  <div class="col-md-5"></div>
    <div class="col-md-2 mx-auto text-left">
      <%= paginate @orders %>
    </div>
  <div class="col-md-5"></div>
</div>

app/views/admin/orders/show.html.erb
<div class="col-2 offset-2 mt-4">
  <h4 class="ml-3 mr-5 text-center" style="background:#ddd">注文履歴詳細</h4>
</div>

<div class="container">
  <div class="row">
    <div class="col-12">
      <%= form_with model: [:admin, @order] do |f| %>
        <table class="table table-borderless">
          <tr>
            <th style="width: 10%"><strong>購入者</strong></th>
            <td>
              <%= link_to customer_admin_order_path(@order.id), class:"text-dark" do %>
                <%= @order.customer.last_name + @order.customer.first_name %>
              <% end %>
            </td>
          </tr>
          <tr>
            <th><strong>注文日</strong></th>
            <td><%= l @order.created_at %></td>
          </tr>
          <tr>
            <th><strong>配送先</strong></th>
            <td>
              <%= @order.shipping_postal_code %>
              <%= @order.shipping_address %><br>
              <%= @order.shipping_name %>
            </td>
          </tr>
          <tr>
            <th><strong>支払方法</strong></th>
            <td><%= @order.payment_way_i18n %></td>
          </tr>
          <tr>
            <th><strong>注文ステータス</strong></th>
            <td class="align-middle">
              <%= f.select :order_status, Order.order_statuses_i18n.invert, {}, class:"form-control d-inline-block", style:"width: 13%" %>
              <%= f.submit "更新", class:"btn btn-success d-inline-block ml-4" %>
            </td>
          </tr>
        </table>
      <% end %>
    </div>

    <div class="col-8">
      <table class="table table-borderless">
        <thead class="table-secondary">
          <tr>
            <th><strong>商品名</strong></th>
            <th class="text-center" style="width: 20%"><strong>単価（税込）</strong></th>
            <th style="width: 10%"><strong>数量</strong></th>
            <th style="width: 10%"><strong>小計</strong></th>
            <th class="text-center" style="width: 20%"><strong>製作ステータス</strong></th>
            <th style="width: 10%"></th>
          </tr>
        </thead>
        <% @sum = 0 %>
        <% @order_details.each do |order_detail| %>
          <%= form_with model: [:admin, order_detail], url: admin_order_detail_path(order_detail.id) do |f| %>
            <% @sum += order_detail.item.add_tax_price %>
            <% @sum *= order_detail.quantity %>
            <tbody>
              <tr>
                <td><%= order_detail.item.name %></td>
                <td class="text-center"><%= order_detail.item.add_tax_price %></td>
                <td class="text-center"><%= order_detail.quantity %></td>
                <td><%= order_detail.item.add_tax_price * order_detail.quantity %></td>
                <td>
                  <%= f.hidden_field :order_id, value: order_detail.order_id %>
                  <%= f.select :product_status, OrderDetail.product_statuses_i18n.invert, {}, class:"form-control" %>
                </td>
                <td><%= f.submit "更新", class:"btn btn-success" %></td>
              </tr>
            </tbody>
          <% end %>
        <% end %>
      </table>
    </div>

    <div class="col-3 px-4 offset-1 align-self-end">
      <table class="table table-borderless">
        <tr>
          <th><strong>商品合計</strong></th>
          <td><%= @sum %>円</td>
        </tr>
        <tr>
          <th><strong>送料</strong></th>
          <td><%= @order.postage %>円</td>
        </tr>
        <tr>
          <th><strong>請求金額合計</strong></th>
          <td><%= @order.total %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>