config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "about"=>"homes#about"
    get "search" => "searches#search"
    resources :items, only: [:index,:show]
    resources :genres, only: [:show]
    resource :customers, only: [] do
      member do
        get :my_page, action: :show
        get 'information/edit', action: :edit
        patch :information, action: :update
        get :confirm
        patch :withdraw
      end
    end
    resources :cart_items, except: [:new,:show,:edit] do
      collection do
        delete :all_destroy
      end
    end
    resources :orders, except: [:edit,:update,:destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
    resources :shipping_addresses, except: [:new,:show]
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update] do
      member do
        get :customer
      end
    end
    resources :order_details, only: [:update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :admin_login_confirm
  
  def index
    @genre_new = Genre.new
    @genres = Genre.all
  end

  def create
    genre_new = Genre.new(genre_params)
    if genre_new.save
      redirect_to request.referer
    else
      @genre_new = Genre.new
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def show
    @genre = Genre.find(params[:id])
    @items = Item.where("genre_id LIKE?", "#{@genre.id}").page(params[:page]).per(10) #10項目毎にページネート
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path(genre)
    else
      @genre = Genre.find(params[:id])
      render "edit"
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/_form.html.erb
<%= form_with model: [:admin, genre] do |f| %>
  <strong><%= f.label :ジャンル名, class:"mr-5" %></strong>
  <%= f.text_field :genre_name, placeholder: "ジャンル名", class:"mr-5" %>

  <% if current_page?(controller: "admin/genres", action: "index") %>
    <%= f.submit "新規登録", class:"btn btn-success btn-lg" %>
  <% else %>
    <%= f.submit "変更を保存", class:"btn btn-success btn-lg" %>
  <% end %>
<% end %>

app/views/admin/genres/_index.html.erb
<table class="table">
  <thead class="thead-light">
    <tr>
      <th class="text-center">ジャンル</th>
      <th></th>
    </tr>
  </thead>
  <% genres.each do |genre| %>
    <tbody>
      <tr>
        <td><%= link_to genre.genre_name, admin_genre_path(genre.id) %></td>
        <td class="text-center"><%= link_to '編集する', edit_admin_genre_path(genre), class:"btn btn-success" %></td>
      </tr>
    </tbody>
  <% end %>
</table>

app/views/admin/genres/edit.html.erb
<div class="container mx-5">
  <div class="row">
    <div class="col">
      <h4 class="mt-4 ml-5">ジャンル編集</h4>
      <div class="mt-5 ml-3">
        <%= render 'form', genre: @genre %>
      </div>
    </div>
  </div>
</div>

app/views/admin/genres/index.html.erb
<div class="container mx-5">
  <div class="row">
    <div class="col">
      <h4 class="mt-4 ml-5">ジャンル一覧・追加</h4>
      <div class="mt-5 ml-3">
        <%= render 'form', genre: @genre_new %>
      </div>
    </div>
  </div>

  <div class="col-5 mt-5">
    <%= render 'index', genres: @genres %>
  </div>
</div>

app/views/admin/genres/show.html.erb
<div class="container">
  <div class="m-md-2"><br>
  <div class="row">
    <h4 class="col-md-2 mx-auto text-center" style="background-color:#DDD">
      <strong><%= @genre.genre_name %>一覧</strong>
    </h4>
    <div class="col-md-5 mx-auto text-right"></div>
  </div>

  <diV class="m-md-2"><br></diV>

  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-1 mx-auto text-left">
      <strong>商品ID</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>商品名</strong>
    </div>
    <div class="col-md-1 mx-auto text-left">
      <strong>税抜価格</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>ジャンル</strong>
    </div>
    <div class="col-md-2 mx-auto text-left">
      <strong>ステータス</strong>
    </div>
    <div class="col-md-1"></div>
  </div>

  <% @items.each do |item| %>
  <div class="row">
    <div class="col-md-1"></div>
    <div class="col-md-1 mx-auto text-left"><%= item.id %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= link_to item.name, admin_item_path(item.id) %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-1 mx-auto text-left"><%= item.price.to_s(:delimited) %>
      <div class="col-md-1"><br></div>
    </div>
    <div class="col-md-2 mx-auto text-left"><%= item.genre.genre_name %>
      <div class="col-md-1"><br></div>
    </div>
    <% if item.is_active == true %>
      <div class="col-md-2 mx-auto text-left text-success">
        <strong><%= '販売中' %></strong>
      </div>
    <% else %>
      <div class="col-md-2 mx-auto text-left text-secondary">
        <strong><%= '販売停止中' %></strong>
      </div>
    <% end %>
    <div class="col-md-1"></div>
  </div>
  <% end %>

  <!--ページネーション追加-->
  <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2 mx-auto text-left">
      <%= paginate @items %>
    </div>
    <div class="col-md-5"></div>
  </div>

</div>