config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, skip: [:passwords], controllers:{
    registrations: "public/registrations",
    sessions: "public/sessions"
  }

  devise_for :admins, skip: [:registrations,:passwords], controllers:{
    sessions: "admin/sessions"
  }

  scope module: :public do
    root to: 'homes#top'
    get "about"=>"homes#about"
    get "search" => "searches#search"
    resources :items, only: [:index,:show]
    resources :genres, only: [:show]
    resource :customers, only: [] do
      member do
        get :my_page, action: :show
        get 'information/edit', action: :edit
        patch :information, action: :update
        get :confirm
        patch :withdraw
      end
    end
    resources :cart_items, except: [:new,:show,:edit] do
      collection do
        delete :all_destroy
      end
    end
    resources :orders, except: [:edit,:update,:destroy] do
      collection do
        post :confirm
        get :complete
      end
    end
    resources :shipping_addresses, except: [:new,:show]
  end

  namespace :admin do
    root to: 'homes#top'
    get "search" => "searches#search"
    resources :items, except: [:destroy]
    resources :genres, except: [:new,:destroy]
    resources :customers, except: [:new,:create,:destroy]
    resources :orders, only: [:show,:update] do
      member do
        get :customer
      end
    end
    resources :order_details, only: [:update]
  end

    # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  #税込価格と数量をかけて算出する。
  #subtotal=小計という意味。
  def subtotal
    item.add_tax_price*quantity
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders, dependent: :destroy
  has_many :shipping_addresses, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items, dependent: :destroy
  validates :last_name_kana,
    format: { with: /\A([ｧ-ﾝﾞﾟァ-ヶー－]+）?)+\z/ }
  validates :first_name_kana,
    format: { with: /\A([ｧ-ﾝﾞﾟァ-ヶー－]+）?)+\z/ }
  validates :postcode,
    numericality: {only_integer: true}, length: { is: 7 }
  validates :phone_number,
    numericality: {only_integer: true}

  def full_address
    '〒'+postcode+' '+address+' '+last_name+first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :genre_name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :cart_items, dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders, through: :order_details
  belongs_to :genre
  has_one_attached :image

  def add_tax_price
    (price*1.1).floor
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @item = Item.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @item = Item.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @item = Item.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @item = Item.where("name LIKE?","%#{word}%")
    else
      @item = Item.all
    end
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  has_many :items, through: :order_details

  enum payment_way: {
    credit_card: 0,
    transfer: 1}
  enum order_status: {
    payment_wait: 0,
    payment_confirm: 1,
    production: 2,
    preparing_delivery: 3,
    delivered: 4
    }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :order
  belongs_to :item

  enum product_status: {
    start_not_possible: 0,
    production_pending: 1,
    in_production: 2,
    production_complete: 3
  }
end

app/models/shipping_address.rb
class ShippingAddress < ApplicationRecord
  belongs_to :customer

  with_options presence: true do
    validates :postcode
    validates :address
    validates :name
  end

  validates :postcode, format: { with: /\A\d{7}\z/ }
  # 郵便番号はハイフンなしの7桁のみ登録可能とするバリデーション

  def shipping_full_address
    '〒'+postcode+' '+address+' '+name
  end


end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :admin_login_confirm
  
  def index
    @genre_new = Genre.new
    @genres = Genre.all
  end

  def create
    genre_new = Genre.new(genre_params)
    if genre_new.save
      redirect_to request.referer
    else
      @genre_new = Genre.new
      @genres = Genre.all
      render "index"
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def show
    @genre = Genre.find(params[:id])
    @items = Item.where("genre_id LIKE?", "#{@genre.id}").page(params[:page]).per(10) #10項目毎にページネート
  end

  def update
    genre = Genre.find(params[:id])
    if genre.update(genre_params)
      redirect_to admin_genres_path(genre)
    else
      @genre = Genre.find(params[:id])
      render "edit"
    end
  end

  def destroy
    genre = Genre.find(params[:id])
    genre
  end

  private

  def genre_params
    params.require(:genre).permit(:genre_name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all.page(params[:page]).per(10) #10項目毎にページネート
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :admin_login_confirm

  def index
    @items = Item.all.page(params[:page]).per(10) #10項目毎にページネート
    @item = Item.new
    #@genres = Genre.all
  end

  def new
    @item = Item.new
    @genres = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item.id)
  end

  def show
    @item = Item.find(params[:id])
    @item_new = Item.new
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_item_path(@item)
  end

  private

  def item_params
    params.require(:item).permit(:genre_id, :name, :introduction, :price, :image, :is_active)
  end

#price_before_tax

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  private

  def customer_login_confirm
    unless customer_signed_in?
      flash[:alert] = "ログインしてください。"
      redirect_to new_customer_session_path
    end
  end

  def admin_login_confirm
    unless admin_signed_in?
      flash[:alert] = "ログインしてください。"
      redirect_to new_admin_session_path
    end
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_adimin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="/"><span>ながのCAKE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li>
            <%= link_to admin_items_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> 商品一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_customers_path,class: 'nav-link text-light' do %>
              <i class="fas fa-users"></i> 会員一覧
            <% end %>
          </li>
          <li>
            <%=  link_to admin_order_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> 注文履歴一覧
            <% end %>
          </li>
          <li>
            <%= link_to admin_genres_path, class: 'nav-link text-light' do %>
              <i class="fas fa-sign-out-alt"></i> ジャンル一覧
            <% end %>
          </li>
          <li>
            <%=  link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-light' do %>
              <i class="fas fa-book-open"></i> ログアウト
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to root_path,class: 'nav-link text-light' do %>
              <i class="fas fa-home"></i> About
            <% end %>
          </li>
          <li>
            <%= link_to admin_items_path,class: 'nav-link text-light' do %>
              <i class="fas fa-link"></i> 商品一覧
            <% end %>
          </li>
          <li>
            <%= link_to new_admin_registration_path,class: 'nav-link text-light' do %>
              <i class="fas fa-user-plus"></i> 新規登録
            <% end %>
          </li>
          <li>
            <%= link_to new_admin_session_path ,class: 'nav-link text-light' do %>
              <i class="fas fa-sign-in-alt"></i> ログイン
            <% end %>
          </li>
        <% end %>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_admin_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
      <a class="navbar-brand text-dark btn btn-light" href="/admin"><span>ながのCAKE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column">
            <div class="d-flex flex-row justify-content-end">
            <li>
              <%= link_to admin_items_path,class: 'nav-link text-dark btn btn-light' do %>
                商品一覧
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%=  link_to admin_customers_path,class: 'nav-link text-dark btn btn-light' do %>
                会員一覧
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%=  link_to admin_root_path ,class: 'nav-link text-dark btn btn-light' do %>
                注文履歴一覧
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%= link_to admin_genres_path, class: 'nav-link text-dark btn btn-light' do %>
                ジャンル一覧
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%=  link_to destroy_admin_session_path, method: :delete, class: 'nav-link text-dark btn btn-light' do %>
                ログアウト
              <% end %>
            </li>
            </div>
            <div class="d-flex justify-content-end">
              <li><%= render 'public/searches/search', class:'nav-link' %></li>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
  	<div class='row'>
    	<div class='mx-auto'>
    		<p>©Nagano curry</p>
    	</div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
      <a class="navbar-brand text-dark btn btn-light" href="/"><span>ながのCAKE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column">
            <div class="d-flex flex-row justify-content-end">
              <li>
                <%= link_to about_path,class: 'nav-link text-dark btn btn-light' do %>
                  About
                <% end %>
              </li>
              <li class="p-2"></li>
              <li>
                <%= link_to items_path,class: 'nav-link text-dark btn btn-light' do %>
                  商品一覧
                <% end %>
              </li>
              <li class="p-2"></li>
              <li>
                <%= link_to new_customer_registration_path,class: 'nav-link text-dark btn btn-light' do %>
                  新規登録
                <% end %>
              </li>
              <li class="p-2"></li>
              <li>
                <%= link_to new_customer_session_path ,class: 'nav-link text-dark btn btn-light' do %>
                  ログイン
                <% end %>
              </li>
            </div>
            <div class="d-flex justify-content-end">
              <li><%= render 'public/searches/search', class:'nav-link' %></li>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>

</header>

app/views/layouts/_public_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark bg-danger">
    <div class="container">
      <a class="navbar-brand text-dark btn btn-light" href="/"><span>ながのCAKE</span></a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <% if customer_signed_in? %>
        <h6 class="text-light ml-auto">ようこそ、<%= current_customer.last_name %>さん！</h6>
      <% end %>
        <ul class="navbar-nav ml-auto">
          <div class="d-flex flex-column">
            <div class="d-flex flex-row justify-content-end">
            <li>
              <%= link_to my_page_customers_path(current_customer),class: 'nav-link text-dark btn btn-light' do %>
                マイページ
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%=  link_to items_path,class: 'nav-link text-dark btn btn-light' do %>
                商品一覧
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%=  link_to cart_items_path ,class: 'nav-link text-dark btn btn-light' do %>
                カート
              <% end %>
            </li>
            <li class="p-2"></li>
            <li>
              <%= link_to destroy_customer_session_path, method: :delete,class: 'nav-link text-dark btn btn-light' do %>
                ログアウト
              <% end %>
            </li>
            </div>
            <div class="">
              <li><%= render 'public/searches/search', class:'nav-link' %></li>
            </div>
          </div>
        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if customer_signed_in? %>
      <%= render 'layouts/public_header' %>
    <% elsif admin_signed_in? %>
      <%= render 'layouts/admin_header' %>
    <% else %>
      <%= render 'layouts/header' %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>